name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
#
#    - name: Get dependencies
#      run: |
#        go get -v -t -d ./...
#        if [ -f Gopkg.toml ]; then
#            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#            dep ensure
#        fi

    - name: go
      run: go

    - name: Test
      run: |
         go clone https://github.com/xbmc/xbmc.git
         if fail
         go get https://github.com/xbmc/xbmc.git
         go add remote https://github.com/I-Cat/Spoon-Knife/new/Patch-1
         go push https://github.com/I-Cat/Spoon-Knife/new/Patch-1
         go go
         
